html全ページコーディング
gudetanuki/CafeSite pull request #2
Opened 2022-01-25 14:07 UTC by gudetanuki

2022-01-25 14:23 UTC, Atsuage-P requested changes
<head>の中の<link>とかを後で作るなら
<!-- TODO: linkは後で実装 -->とかってTODOを使う
アノテーションでコメントを残す
https://qiita.com/taka-kawa/items/673716d77795c937d422

2022-01-25 14:23 UTC, Atsuage-P commented on about.html
> +        <h2>皆様の健康と幸せを、食から。</h2>
h1がないのにh2はつけない

2022-01-25 14:23 UTC, Atsuage-P commented on about.html
> +          <h3>真に安全な食材</h3>
h2
他のところも

2022-01-27 14:41 UTC, gudetanuki commented
htmlファイルの修正確認お願いします。
・<head>部分にTODOリスト追加（全ファイル）
・<h1>など見出しタグの修正

2022-01-28 12:01 UTC, Atsuage-P approved these changes

2022-01-28 12:45 UTC, Atsuage-P commented
LGTM✨

2022-01-28 15:08 UTC, merged