Feature/menupage
gudetanuki/CafeSite pull request #6
Opened 2022-02-10 13:15 UTC by gudetanuki

menuページとフッター部分のコーディングしました。
添削お願いします。

2022-02-10 15:03 UTC, Atsuage-P requested changes

2022-02-10 15:03 UTC, Atsuage-P commented on menu.html
> +  <link rel="stylesheet" href="dict/css/footer.css">
読み込むファイルは一つにまとめる

2022-02-10 15:03 UTC, Atsuage-P commented on menu.html
> +      <div class="lunch-container lunch-container-1">
名前が似すぎて後でどんなcssがついてるのかわかりにくいかも

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +  font-size: 30px;
font-sizeも色々出てくるけど、最初に使う大きさをいくつか決めておいてvariableにまとめておくとデザイン的にもいいかも

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +  flex-direction: row-reverse;
```
.lunch-container
  &__reverse
    flex-direction: row-reverse
```
で`image1` `image2` ...にすればいいのでは

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +      width: 100%;
75行目と被ってる

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +.sweet-container-1-contents {
ここも`image1`, `image2`で事足りそう

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +.drink-name {
&使う

2022-02-10 15:03 UTC, Atsuage-P commented on src/scss/menu.scss
> +.drink-price {
&使う

2022-02-12 07:30 UTC, gudetanuki commented on src/scss/menu.scss
> +  flex-direction: row-reverse;
.flex-row-reverse クラスを作り、要素を逆横並びにしたいdivに当クラスを付与する形にしました。

2022-02-12 10:21 UTC, Atsuage-P requested changes

2022-02-12 10:21 UTC, Atsuage-P commented on src/scss/_font-style.scss
> +// h3タグ用のフォントサイズ
h2は？

2022-02-12 10:21 UTC, Atsuage-P commented on src/scss/_font-style.scss
> +$x-small-font-size: 1.2rem;
ここ一式をvariableに移動させる

2022-02-12 10:21 UTC, Atsuage-P commented on src/scss/_font-style.scss
>    font-size: 3rem;
3remは定義した変数に変える

2022-02-12 10:21 UTC, Atsuage-P commented on src/scss/_font-style.scss
> +$x-large-font-size: 4rem;
font-size-xl
font-size-l
font-size-m
とかの方がいいのでは

2022-02-12 10:21 UTC, Atsuage-P commented on src/scss/menu.scss
>      background-image: url(../../img/menu-image1.jpeg);
このurlもvariableファイルで変数にする

2022-02-12 11:42 UTC, Atsuage-P requested changes

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
>            <h3>30品の野菜健康定食</h3>
h2がないのにh3は使わない
必ずh1から順番に使う

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +      <div class="lunch-container lunch-container-1 flex-row-reverse">
`lunch-container-1`これ使ってる？
使ってないなら消す

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +        <div class="detail lunch-container-detail lunch-container-1-detail">
`lunch-container-1-detail`これも

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +          <div class="lunch-container-contents lunch-container-1-contents">玄米ご飯、塩麹の鳥唐揚げ、<br>
`lunch-container-1-contents`同上

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +          <div class="price">1,100円<span>（税込）</span></div>
`span`にclassつけたらmenu.scssの130,139行目も一つにまとまる

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +      <div class="lunch-container lunch-container-2">
以下、いらないclass削除のこと

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
> +      <div class="drink-menu-list">
上の`sweet-container`に合わせて`drink-container`かな
ちなみに`sweets-container`

2022-02-12 11:42 UTC, Atsuage-P commented on menu.html
>          <div class="drink">
`div`じゃなくて`ul li`にした方がlistとして見やすいしタグ的に正しい

2022-02-12 11:42 UTC, Atsuage-P commented on src/scss/_base.scss
>    font-size: 1.6rem;
`font-size`は変数にしたどれかでは

2022-02-12 11:42 UTC, Atsuage-P commented on src/scss/menu.scss
> +    &-detail {
69行目と同じ
以前のレビューが修正されてない

2022-02-12 11:42 UTC, Atsuage-P commented on src/scss/menu.scss
> +.sweet-container-1-contents {
この辺も修正されてない
`lunch-container`の`image1`とかと同じように修正できるはず

2022-02-12 11:42 UTC, Atsuage-P commented on src/scss/_font-style.scss
>  .heading {
このclassはimportもしてないし使ってなくない？

2022-02-13 01:37 UTC, gudetanuki commented on src/scss/_font-style.scss
>  .heading {
このクラスはトップページで使っている

2022-02-13 02:36 UTC, gudetanuki commented on src/scss/menu.scss
> +    &-detail {
どれの件ですか🐽

2022-02-13 04:45 UTC, Atsuage-P requested changes

2022-02-13 04:45 UTC, Atsuage-P commented on menu.html
> +          <div class="price">1,100円<span class="span">（税込）</span></div>
spanって名前のclassはよくない

2022-02-13 04:45 UTC, Atsuage-P commented on menu.html
> +      <ul class="drink-menu-list">
ここは`div`タグにして`drink-container`
`li`タグのclass名は`drink-item`とか

2022-02-13 04:45 UTC, Atsuage-P commented on src/scss/_base.scss
> +  font-size: $font-size-basic;
basicっていうかbaseかな

2022-02-13 04:45 UTC, Atsuage-P commented on src/scss/_variable.scss
> +$sweet-bkg-image2: url(../../img/sweet-image2.jpeg);
`$lunch-bkg-img1`に合わせるなら`$sweets-bkg-img`

2022-02-13 04:45 UTC, Atsuage-P commented on menu.html
> +        <div class="sweets-container-contents">
こっちも`li`化

2022-02-13 04:45 UTC, Atsuage-P commented on menu.html
>          <div class="lunch-container-image image1"></div>
こっちも`li`化

2022-02-13 04:51 UTC, Atsuage-P requested changes

2022-02-13 04:51 UTC, Atsuage-P commented on src/scss/_base.scss
>    background-image: url(../../img/background.jpeg);
ここも変数にする

2022-02-13 07:51 UTC, Atsuage-P commented
LGTM✨

2022-02-13 07:51 UTC, Atsuage-P approved these changes

2022-02-13 07:54 UTC, merged